if(INK_ENABLE_LTO)
    include(CheckIPOSupported)
    check_ipo_supported(RESULT IPO_SUPPORTED OUTPUT IPO_ERROR)
    if(IPO_SUPPORTED)
        set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE TRUE)
        message(STATUS "[ink] Interprocedural Optimization (LTO) enabled for Release builds")
    else()
        message(STATUS "[ink] LTO requested but not supported: ${IPO_ERROR}")
    endif()
endif()